spring:
  application:
    名字: adg-rule
  profiles:
    已激活: prod  #切换至 dev 即可输出调试信息

logging:
  file:
    path: ./logs

application:
  rule:
    #远程规则
    remote:
      # Adguard
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/adservers.txt' #AdGuard DNS BaseFilter #Combined in AdGuard DNS filter
      #- 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_Base/filter.txt' #AdGuard Base filter #Combined in AdGuard DNS filter
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/adservers_firstparty.txt' #AdGuard BaseFilter — first-party servers
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/content_blocker.txt' #BaseFilter content_blocker
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/allowlist.txt' #BaseFilter allowlist 
      #- 'https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_original_trackers.txt' #cname-trackers adspyglass
      - 'https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt' #AdGuard DNS filter
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/adservers.txt' #AdGuard DNS filter mobile
      #- 'https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_11_Mobile/filter.txt' #AdGuard mobile #Combined in AdGuard DNS filter
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/allowlist_app.txt' #MobileFilter allowlist_app
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/MobileFilter/sections/allowlist_web.txt' #MobileFilter allowlist_web
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/adservers.txt' #AdGuard Chinese filter
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/adservers_firstparty.txt' #AdGuard Chinese filter — first-party servers
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/antiadblock.txt'#ChineseFilter antiadblock
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/allowlist.txt' #ChineseFilter allowlist
      
      # EasyList
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_adservers.txt' #EasyList
      #- 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_thirdparty.txt' #EasyList — third-party servers
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easylist/easylist_allowlist.txt' #easylist - allowlist
      - 'https://raw.githubusercontent.com/easylist/easylistchina/master/easylistchina.txt' #EasyList China
      
      # Tracking Server
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/SpywareFilter/sections/tracking_servers.txt' #AdGuard Tracking Protection filter — third-party trackers
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/SpywareFilter/sections/tracking_servers_firstparty.txt' #AdGuard Tracking Protection filter — first-party trackers
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/SpywareFilter/sections/allowlist.txt' #AdGuard Tracking Protection filter - allowlist
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/SpywareFilter/sections/mobile_allowlist.txt' #AdguardFilters SpywareFilter mobile - allowlist
      #- 'https://filters.adtidy.org/extension/ublock/filters/3_optimized.txt' #AdGuard Tracking Protection filter 
      #- 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/SpywareFilter/sections/mobile.txt' #AdguardFilters SpywareFilter mobile
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers.txt' #EasyPrivacy
      - 'https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_thirdparty.txt' #EasyPrivacy third party
      # - 'https://raw.githubusercontent.com/bongochong/CombinedPrivacyBlockLists/master/cpbl-abp-list.txt' #bongochong/CombinedPrivacyBlockLists
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.amazon.txt' #Amazon
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.apple.txt' #Apple
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.huawei.txt' #Huawei
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.winoffice.txt' #MS
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.samsung.txt' #Samsung
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.tiktok.txt' #TikTok (Fingerprinting)
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.tiktok.extended.txt' #TikTok (Fingerprinting) Aggressive
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.lgwebos.txt' #LG webOS
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.roku.txt' #Roku
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.vivo.txt' #VIVO
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.oppo-realme.txt' #OPPO/Realme
      - 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/native.xiaomi.txt' #Xiaomi
      
      # Cryptominers
      - 'https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/cryptominers.txt' #AdGuard Cryptominers
      - 'https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt' #hoshsadiq/adblock-nocoin-list
      
      # Malicious URLs
      - 'github.com/AdguardTeam/HostlistsRegistry/raw/refs/heads/main/assets/filter_11.txt' #Adguard malicious URLs
      #- 'https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/spam-tlds.txt' #hagezi - Top Most Abused Top Level Domains
      
      # Others
      #- 'https://raw.githubusercontent.com/durablenapkin/scamblocklist/master/adguard.txt' #durablenapkin/scamblocklist
      #- 'https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext' #Peter Lowe's List
      # - 'https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt' #Adgk
      #- 'https://raw.githubusercontent.com/badmojr/1Hosts/master/Lite/adblock.txt' #1Hosts
      #- 'https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt' #Cats-Team/AdRules
      - 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt' #AWAvenue Ads Rule
      - 'https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt' #damengzhu/banad
      - 'https://raw.githubusercontent.com/FutaGuard/LowTechFilter/master/hosts.txt' #FutaGuard/LowTechFilter - hosts
      - 'https://filter.futa.gg/TW165_abp.txt' #FutaGuard/LowTechFilter - LowTechHost
      #- 'https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Formats/GoodbyeAds-AdBlock-Filter.txt' #jerryn70/GoodbyeAds
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/refs/heads/master/mv.txt' #乘风视频过滤规则
      - 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/refs/heads/master/rule.txt' #乘风通用过滤规则
      - 'https://easylist-downloads.adblockplus.org/fanboy-social.txt' #Fanboy's Social Blocking List 禁止社交媒体图标列表
      - 'https://raw.githubusercontent.com/cjx82630/cjxlist/refs/heads/master/cjx-annoyance.txt' #cjx-annoyance
      - 'https://raw.githubusercontent.com/cjx82630/cjxlist/refs/heads/master/cjxlist.txt' #cjxlist
      - 'https://raw.githubusercontent.com/ilpl/ad-hosts/refs/heads/master/hosts' #ilpl/ad-hosts 偏向小说网站
      - 'https://raw.githubusercontent.com/BlackJack8/iOSAdblockList/refs/heads/master/Hosts.txt' #BlackJack8/iOSAdblockList
      - 'http://rssv.cn/adguard/api.php?type=black' #晴雅
      - 'https://perflyst.github.io/PiHoleBlocklist/SmartTV-AGH.txt' #PiHoleBlocklist/SmartTV-AGH
      - 'https://raw.githubusercontent.com/Noyllopa/NoAppDownload/master/NoAppDownload.txt' #Noyllopa/NoAppDownload
      - 'https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/regex.txt' #afwfv/DD-AD regex
      
      #白名单
      - 'https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/DD-AD.txt' #afwfv/DD-AD
      
      # 整合性项目
      #- 'https://raw.githubusercontent.com/o0HalfLife0o/list/master/ad-pc.txt' #HalfLife（pc）
      #- 'https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-easylist.txt' #anti-AD
      #- 'https://hblock.molinero.dev/hosts_adblock.txt' #hectorm/hblock
      #- 'https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt' #adblockfilters
      #- 'https://raw.githubusercontent.com/neodevpro/neodevhost/master/adblocker' #neodevhost 整合了Ad-wars, Anti-ad, StevenBlack
      #- 'https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt' #217heidai/adblockfilters
      #- 'https://raw.githubusercontent.com/5-whys/adh-rules/main/rules/output_medium.txt' #/5-whys/adh-rules - medium
      #- 'https://raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/dns.txt' #8680/GOODBYEADS
      
    #本地规则
    local: #本地规则请将文件移动到项目路径rule目录中
      - 'mylist.txt'
  output:
    path: rule   #规则文件输出路径，相对路径默认从 项目目录开始
    files:
      all.txt:    #输出文件名
        - DOMAIN  #域名规则，仅完整域名
        - REGEX   #正则规则，包含正则的域名规则，AdGH支持
        - MODIFY  #修饰规则，添加了一些修饰符号的规则，AdG支持
        - HOSTS   #Hosts规则
      adgh.txt:
        - DOMAIN
        - REGEX
#        - HOSTS
      hosts.txt:
        - HOSTS
      regex.txt:
        - REGEX
      domain.txt:
        - DOMAIN
      modify.txt:
        - MODIFY
